# hebidu custom config
hebidu:
  json:
    prop_naming_style: snake_case

# logging
# tomcat config
server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
# spring config
spring:
  banner:
    location: classpath:banner.txt
  mvc:
    favicon:
      enabled: false
  application:
    name: default.app
  jpa:
    open-in-view: false
# datasource config
  datasource:
    url: jdbc:mysql://47.88.216.242/bookstore?characterEncoding=utf8&useSSL=false
    username: hebidu
    password: 364945361
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
# actuator config
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: ["health","info","shutdown"]
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  server:
    port: 54001
logging:
  file: spring.log